name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Cypress Tests
      - name: Checkout Cypress Tests
        uses: actions/checkout@v3

      # Step 2: Clone Backend Project (Using HTTPS)
      - name: Clone Backend Project
        run: |
          git clone https://github.com/velevtzvetlin/express-mock-interview.git backend
          if [ -d "backend" ]; then
            echo "✅ Backend cloned successfully"
          else
            echo "❌ Backend clone failed"
            exit 1
          fi

      # Step 3: Clone Frontend Project (Using HTTPS)
      - name: Clone Frontend Project
        run: |
          git clone https://github.com/velevtzvetlin/fe-test-task.git frontend
          if [ -d "frontend" ]; then
            echo "✅ Frontend cloned successfully"
          else
            echo "❌ Frontend clone failed"
            exit 1
          fi

      # Step 4: Debugging - Check Directory Structure Before CD
      - name: Verify Backend Directory Exists
        run: |
          ls -la
          if [ ! -d "backend" ]; then
            echo "❌ Backend directory is missing!"
            exit 1
          fi

      # Step 5: Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
        working-directory: ./backend
