name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting CI pipeline..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js and npm Version
        run: |
          node -v
          npm -v

      # ✅ Clone and Start Backend (express-mock-interview)
      - name: Clone Backend Repository
        run: git clone https://github.com/velevtzvetlin/express-mock-interview.git backend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Start Backend Server
        working-directory: ./backend
        run: npm start &
        shell: bash

      # ✅ Clone and Start Frontend (fe-test-task)
      - name: Clone Frontend Repository
        run: git clone https://github.com/velevtzvetlin/fe-test-task.git frontend

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm run dev &
        shell: bash

      - name: Wait for Servers to Start
        run: sleep 20s

      # ✅ Ensure Cypress Binary is Installed
      - name: Install Cypress Binary
        run: npx cypress install

      # ✅ Run Cypress Tests in Edge
      - name: Run Cypress Tests in Edge
        run: npx cypress run --browser edge

      - name: Complete job
        run: echo "CI pipeline finished!"
