name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Cypress Tests
      - name: Checkout Cypress Tests
        uses: actions/checkout@v3

      # Step 2: Clone Backend Project (Using GitHub Token for Authentication)
      - name: Clone Backend Project
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/velevtzvetlin/express-mock-interview.git backend
          ls -la backend || echo "⚠️ Backend repo not cloned!"

      # Step 3: Clone Frontend Project (Using GitHub Token for Authentication)
      - name: Clone Frontend Project
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/velevtzvetlin/fe-test-task.git frontend
          ls -la frontend || echo "⚠️ Frontend repo not cloned!"

      # Step 4: Debugging - Verify Directory Structure
      - name: Debugging - Check Directory Structure
        run: ls -la

      # Step 5: Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
        working-directory: ./backend

      # Step 6: Start Backend Server
      - name: Start Backend Server
        run: |
          cd backend
          npm start &
        working-directory: ./backend

      # Step 7: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci
        working-directory: ./frontend

      # Step 8: Start Frontend Server
      - name: Start Frontend Server
        run: |
          cd frontend
          npm run dev &
        working-directory: ./frontend

      # Step 9: Wait for Servers to Start
      - name: Wait for Servers to Start
        run: sleep 20 # Adjust this based on how long your FE/BE take to start

      # Step 10: Install Cypress Dependencies
      - name: Install Cypress Dependencies
        run: npm ci

      # Step 11: Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run
