name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting CI pipeline..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js and npm Version
        run: |
          node -v
          npm -v

      - name: Install Google Chrome
        run: choco install googlechrome -y

      - name: Verify Google Chrome Installation
        run: |
          if (!(Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe")) {
            Write-Error "Chrome not found!"
            exit 1
          }
          Write-Output "Chrome installed successfully."

      - name: Check Chrome Version
        run: |
          "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
        shell: cmd


      - name: Add Chrome to PATH
        run: |
          echo "C:\Program Files\Google\Chrome\Application" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Clone Backend Project
        run: git clone https://github.com/your-org/backend-repo.git backend

      - name: Clone Frontend Project
        run: git clone https://github.com/your-org/frontend-repo.git frontend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Backend Server
        working-directory: ./backend
        run: |
          npm start &
        shell: bash

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start Frontend Server
        working-directory: ./frontend
        run: |
          npm start &
        shell: bash

      - name: Wait for Servers to Start
        run: sleep 20s

      - name: Install Cypress Dependencies
        run: npm install cypress --save-dev

      - name: Run Cypress Tests in Google Chrome
        run: npx cypress run --browser chrome

      - name: Post Checkout Cypress Tests
        run: echo "Cypress tests completed."

      - name: Complete job
        run: echo "CI pipeline finished!"
