name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-2022

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies in Backend
      - name: Install backend dependencies
        run: |
          git clone https://github.com/velevtzvetlin/express-mock-interview.git backend
          cd backend
          npm ci

      # Install dependencies in Frontend
      - name: Install frontend dependencies
        run: |
          git clone https://github.com/velevtzvetlin/fe-test-task.git frontend
          cd frontend
          npm ci

      # Run the backend server
      - name: Start backend server
        run: |
          cd backend
          npm start &
        shell: bash

      # Run the frontend server
      - name: Start frontend server
        run: |
          cd frontend
          npm run dev &
        shell: bash

      # Sleep for 20 seconds to ensure the servers are up and running
      - name: Wait for servers to start
        run: sleep 20s

      # Install Cypress and Allure dependencies
      - name: Install Cypress and Allure dependencies
        run: |
          npm install -D @shelex/cypress-allure-plugin allure-commandline
          npx cypress install

      # Run Cypress tests with Allure enabled
      - name: Run Cypress Tests with Allure
        run: npx cypress run --browser edge --env allure=true,allureResults=allure-results

      # Generate Allure report if results are available
      - name: Generate Allure Report
        run: |
          mkdir -p allure-results allure-report
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            npx allure generate allure-results --clean -o allure-report
          else
            echo "⚠️ Warning: No Allure results found! Skipping report generation."
            exit 0
          fi
        shell: bash

      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      # Trigger Allure Report Deployment Workflow
      - name: Trigger Allure Report Deployment Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'deploy-allure-report.yml'
          ref: 'main'
