name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting CI pipeline..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js and npm Version
        run: |
          node -v
          npm -v

      - name: Clone Backend Project
        run: git clone https://github.com/your-org/backend-repo.git backend

      - name: Clone Frontend Project
        run: git clone https://github.com/your-org/frontend-repo.git frontend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Backend Server
        working-directory: ./backend
        run: npm start &
        shell: bash

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm start &
        shell: bash

      - name: Wait for Servers to Start
        run: sleep 20s

      - name: Install Cypress Dependencies
        run: npm install cypress --save-dev

      # ✅ Run Cypress Tests in Edge (No Version Check Needed)
      - name: Run Cypress Tests in Edge
        run: npx cypress run --browser edge

      - name: Complete job
        run: echo "CI pipeline finished!"
