name: Run Cypress Tests on Windows (Chrome)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Cypress Tests
      - name: Checkout Cypress Tests
        uses: actions/checkout@v3

      # Step 2: Upgrade Node.js to v20
      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Upgrade to Node.js 20

      # Step 3: Install Google Chrome
      - name: Install Chrome
        run: choco install googlechrome -y

      # Step 4: Verify Chrome Installation (Windows-friendly)
      - name: Check Chrome Version
        run: |
          Get-Command "C:\Program Files\Google\Chrome\Application\chrome.exe" | Select-Object VersionInfo
        shell: pwsh

      # Step 5: Clone Backend Project
      - name: Clone Backend Project
        run: |
          git clone https://github.com/velevtzvetlin/express-mock-interview.git backend
          if (Test-Path "backend") {
            Write-Host "✅ Backend cloned successfully"
          } else {
            Write-Host "❌ Backend clone failed"
            exit 1
          }

      # Step 6: Clone Frontend Project
      - name: Clone Frontend Project
        run: |
          git clone https://github.com/velevtzvetlin/fe-test-task.git frontend
          if (Test-Path "frontend") {
            Write-Host "✅ Frontend cloned successfully"
          } else {
            Write-Host "❌ Frontend clone failed"
            exit 1
          }

      # Step 7: Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      # Step 8: Start Backend Server
      - name: Start Backend Server
        run: |
          cd backend
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "start"

      # Step 9: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # Step 10: Start Frontend Server
      - name: Start Frontend Server
        run: |
          cd frontend
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run dev"

      # Step 11: Wait for Servers to Start
      - name: Wait for Servers to Start
        run: Start-Sleep -s 20

      # Step 12: Force Install `cypress-xpath`
      - name: Force Install cypress-xpath
        run: |
          npm install cypress-xpath --legacy-peer-deps --force

      # Step 13: Install Cypress Dependencies
      - name: Install Cypress Dependencies
        run: npm ci

      # Step 14: Run Cypress Tests in Chrome
      - name: Run Cypress Tests in Google Chrome
        run: npx cypress run --browser chrome --headless
