name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Cypress Tests
        uses: actions/checkout@v3

      - name: Clone Backend Project
        run: |
          git clone https://github.com/velevtzvetlin/express-mock-interview.git backend
          ls -la backend  # Debugging step to check if the repository exists

      - name: Clone Frontend Project
        run: |
          git clone https://github.com/velevtzvetlin/fe-test-task.git frontend
          ls -la frontend  # Debugging step to check if the repository exists

      - name: Install Backend Dependencies
        run: |
          cd backend || exit 1
          npm ci
        working-directory: ./backend

      - name: Start Backend Server
        run: |
          cd backend || exit 1
          npm start &
        working-directory: ./backend

      - name: Install Frontend Dependencies
        run: |
          cd frontend || exit 1
          npm ci
        working-directory: ./frontend

      - name: Start Frontend Server
        run: |
          cd frontend || exit 1
          npm run dev &
        working-directory: ./frontend

      - name: Wait for Servers to Start
        run: sleep 20 # Adjust if needed

      - name: Install Cypress Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run
