name: Run Cypress Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting CI pipeline..."
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js and npm Version
        run: |
          node -v
          npm -v

      # ✅ Clone and Start Backend (express-mock-interview)
      - name: Clone Backend Repository
        run: git clone https://github.com/velevtzvetlin/express-mock-interview.git backend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Start Backend Server
        working-directory: ./backend
        run: npm start &
        shell: bash

      # ✅ Clone and Start Frontend (fe-test-task)
      - name: Clone Frontend Repository
        run: git clone https://github.com/velevtzvetlin/fe-test-task.git frontend

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm run dev &
        shell: bash

      - name: Wait for Servers to Start
        run: sleep 20s

      # ✅ Install Cypress and Allure dependencies
      - name: Install Cypress and Allure dependencies
        run: |
          npm install -D @shelex/cypress-allure-plugin allure-commandline
          npx cypress install

      # ✅ Run Cypress Tests with Allure in Edge (headed mode for debugging)
      - name: Run Cypress Tests with Allure (headed mode)
        run: |
          npx cypress run --browser msedge --headed --env allure=true,allureResults=allure-results

      # ✅ Generate Allure Report
      - name: Generate Allure Report
        run: |
          mkdir -p allure-results allure-report
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            npx allure generate allure-results --clean -o allure-report
          else
            echo "⚠️ Warning: No Allure results found! Skipping report generation."
            exit 0
          fi
        shell: bash

      # ✅ Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Complete job
        run: echo "CI pipeline finished!"
