name: Run Cypress Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Set up job
        run: echo "Starting CI pipeline..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Check Node.js and npm Version
        run: |
          node -v
          npm -v

      - name: Clone Backend Repository
        run: git clone https://github.com/velevtzvetlin/express-mock-interview.git backend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Start Backend Server
        working-directory: ./backend
        run: npm start &
        shell: bash

      - name: Clone Frontend Repository
        run: git clone https://github.com/velevtzvetlin/fe-test-task.git frontend

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm run dev &
        shell: bash

      - name: Wait for Servers to Start
        run: sleep 20s

      - name: Install Allure for Cypress
        run: npm install -D @shelex/cypress-allure-plugin allure-commandline

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Run Cypress Tests with Allure in Edge
        run: npx cypress run --browser edge --env allure=true

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Complete job
        run: echo "CI pipeline finished!"
