name: Run Cypress Tests on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Switch to Windows instead of Ubuntu

    steps:
      # Step 1: Checkout Cypress Tests
      - name: Checkout Cypress Tests
        uses: actions/checkout@v3

      # Step 2: Clone Backend Project (Using HTTPS)
      - name: Clone Backend Project
        run: |
          git clone https://github.com/velevtzvetlin/express-mock-interview.git backend
          if (Test-Path "backend") {
            Write-Host "✅ Backend cloned successfully"
          } else {
            Write-Host "❌ Backend clone failed"
            exit 1
          }

      # Step 3: Clone Frontend Project (Using HTTPS)
      - name: Clone Frontend Project
        run: |
          git clone https://github.com/velevtzvetlin/fe-test-task.git frontend
          if (Test-Path "frontend") {
            Write-Host "✅ Frontend cloned successfully"
          } else {
            Write-Host "❌ Frontend clone failed"
            exit 1
          }

      # Step 4: Debugging - Check Directory Structure Before CD
      - name: Verify Backend Directory Exists
        run: |
          Get-ChildItem
          if (!(Test-Path "backend")) {
            Write-Host "❌ Backend directory is missing!"
            exit 1
          }

      # Step 5: Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      # Step 6: Start Backend Server
      - name: Start Backend Server
        run: |
          cd backend
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "start"

      # Step 7: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # Step 8: Start Frontend Server
      - name: Start Frontend Server
        run: |
          cd frontend
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run dev"

      # Step 9: Wait for Servers to Start
      - name: Wait for Servers to Start
        run: Start-Sleep -s 20  # Equivalent of sleep in PowerShell

      # Step 10: Install Cypress Dependencies
      - name: Install Cypress Dependencies
        run: npm ci

      # Step 11: Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run
